server:
  address: "localhost"
  port: 8315
database:
  path: "D:\\MyConfiguration\\RTP8320"
infobase:
  id: "d6e75ec4-435f-4751-97c6-9f9f4e11b286"
  name: "RTP8320"
http:
- base: "/"
gates:
  ssh:
    admin:
      address: "localhost"
      port: 1543
      host-key: "D:\\MyConfiguration\\GitRepo\\Серверы\\Автономный сервер 8.3.20.1613\
        \ @ localhost-config\\.ssh\\id_rsa"
