server:
  address: "localhost"
  port: 8315
database:
  path: "D:\\Works\\MyConfiguration\\ibs\\RTPAC8320"
infobase:
  id: "f3639fca-685f-4b66-978b-13564e9ce525"
  name: "RTP8320"
http:
- base: "/"
gates:
  ssh:
    admin:
      address: "localhost"
      port: 1543
      host-key: "D:\\Works\\MyConfiguration\\GitRepo\\Серверы\\Автономный сервер 8.3.20.1613\
        \ @ localhost-config\\.ssh\\id_rsa"
